using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CapstoneProject.Models
{
    public static class AllTriggerWords
    {
    //    foreach(string s in AllTriggerWords.allWords)
    //        {
    //            var newFood = new NonVeganFood() { Keyword = s };
    //    await _context.NonVeganFoods.AddAsync(newFood);
    //}
    //await _context.SaveChangesAsync();

    public static List<string> allWords = new List<string>() { "Adrenaline",
"Alanine",
"Albumen",
"Alcloxa",
"Allantoin",
"Ambergris",
"Aspartic Acid",
"Animal Fats and Oils",
"Arachidonic Acid",
"Bee Pollen",
"Beeswax (Honeycomb)",
"Biotin",
"Boar Bristles",
"Bone Char",
"Bone Meal",
"Calciferol",
"Caprylic Acid",
"Carbamide (Urea)",
"Carmine",
"Cashmere",
"Castor (Castoreum)",
"Catgut",
"Cerebrosides",
"Cetyl Alcohol",
"Cetyl Palmitate",
"Chitosan",
"Cholesterin",
"Cholesterol",
"Choline Bitartrate",
"Civet",
"Cod Liver Oil",
"Collagen",
"Cortisone",
"Corticosteroid",
"Cystine",
"Dexpanthenol",
"Diglycerides",
"Down",
"Elastin",
"Egg",
"Egg white",
"Egg whites",
"Egg yolk",
"Eggnog",
"Mayonnaise",
"Meringue",
"Ovalbumin",
"Surimi",
"Emu Oil",
"Ergocalciferol",
"Estrogen",
"Estradiol",
"Fatty Acids",
"Feathers",
"Fur",
"Glycerin",
"Glycerol",
"Guanine",
"Pearl Essence",
"Honey",
"Horsehair",
"Isinglass",
"Isopropyl Myristate",
"Keratin",
"Lactic Acid",
"Lactose",
"Lanolin",
"Wool Fat",
"Wool Wax",
"Lanosterols",
"Lard",
"Leather",
"Suede",
"Calfskin",
"Sheepskin",
"Lecithin",
"Linoleic Acid",
"Lipase",
"Lipids",
"Lipoids",
"Methionine",
"Mink Oil",
"Monoglycerides",
"Musk",
"Nucleic Acids",
"Oleic Acid",
"Oleyl Alcohol",
"Ocenol",
"Oleths",
"Palmitic Acid",
"Panthenol",
"Dexpanthenol",
"Vitamin B-Complex Factor",
"Provitamin B-5",
"Pepsin",
"Placenta",
"Placenta Polypeptides Protein",
"Polyglycerol",
"Polysorbates",
"Pristane",
"Progesterone",
"Propolis",
"Resinous Glaze",
"Retinol",
"RNA",
"Ribonucleic Acid",
"Royal Jelly",
"Sable",
"Shellac",
"Silk",
"Sodium Stearoyl Lactylate",
"Spermaceti. Cetyl Palmitate. Sperm Oil",
"Squalane",
"Stearates",
"Stearic Acid",
"Sterol",
"Triterpene Alcohols",
"Tyrosine",
"Wool",
"Ammonium Caseinate","Butter","Butter Fat","Butter Oil","Butter Solids","Acidophilus Milk","Buttermilk","Buttermilk Powder","Calcium Caseinate","Casein","Caseinate (in general)","Cheese(All animal-based)","Condensed Milk","Cottage Cheese","Cream","Curds","Custard","Delactosed Whey","Demineralized Whey","Dry Milk Powder","Dry Milk Solids","Evaporated Milk",
"Goat Cheese","Ghee","Goat Milk","Half & Half","Hydrolyzed Casein","Hydrolyzed Milk Protein","Iron Caseinate","Lactalbumin","Lactoferrin","Lactoglobulin","Lactose","Lactulose","Low-Fat Milk","Magnesium Caseinate","Malted Milk","Milk","Milk Derivative","Milk Fat","Milk Powder","Milk Protein","Milk Solids","Natural Butter Flavor","Nonfat Milk","Nougat","Paneer",
"Potassium Caseinate","Pudding","Recaldent","Rennet Casein","Sheep Milk","Sheep Milk Cheese","Skim Milk","Sodium Caseinate","Sour Cream","Sour Milk Solids","Sweetened Condensed Milk","Sweet Whey","Whey","Whey Powder","Whey Protein Concentrate","Whey Protein Hydrolysate","Whipped Cream","Whipped Topping","Whole Milk","Yogurt","Zinc Caseinate",
 };


}
}
